print("Tüm hakları bana aittir. Olaylar, kişiler ve herşey tamamen hayalidir.")

input("\n Kardeşini bulmak için biraz genişçe olan yoldan Emir ile yürüyorsun.")
input("\n \"Sağol knk hemen geldin.\" ")
input("\n	\"Önemli değil knk. Hem macera oluyor uzun süredir hep bi macera istemiştim. Ama kardeşin için değil, ona üzüldüm baya.\"")
input("\n Yaklaşık 1 saattir yürüyorsunuz.")
input("\n	\"Knk ne kadar yolumuz var? Ben hafiften yorulmaya başladım.\"")
input("\n \"Hiç bilmiyorum knk. Biz gittikçe o uzaklaşıyor. Ara vermek isterdim ama aradaki mesafe artarsa kaybedebiliriz.\"")
input("\n	\"Neyse, en azından yanımda biraz yiyecek ve içecek de vardı. Al biraz iç.\"")
input("\n \"Eyw.\"")
input("\n Emir'in verdiği meyve suyundan içerken enerjinin yerine geldiğini hissediyorsun.")
input("\n Meyve suyunun dibini \"Hüüüüfpffpfp\" diye çekerken, elindeki fener ışığının büyüdüğünü ve önünde kendi gölgenin olduğunu farkediyorsun.")
input("\n Aniden, hayal sandığın aracın sesi hızla yakınlaşıyor.")
input("\n İçinden bir ses, hiçbir şeyin yolunda olmadığını söylüyor.")
input("\n \"EMİR KOŞ!\"")
input("\n Harekete geçene kadar, araçtan 2 adam gelip yüzünüze garip kokulu bir bez bastırıyor.")
input("\n Yavaşça kendinden geçiyorsun.")
input("\n ...")
input("\n	\"Vay canına! bu kadar becerikli olduğunuzu bilmiyordum. Aferin, 1 taşla 3 kuş vurduk!\"")
input("\n Yavaşça kendine gelirken bu yabancı sesle uyanıyorsun.")
input("\n Hemen Emir'i kontrol ediyorsun.")
input("\n Hala baygın.")
input("\n Bir süre sarsıldıktan sonra uyanıyor.")
input("\n	\"Ne oldu bize?\"")
input("\n \"Kaçırıldık.\"")
input("\n	\"Bir planın var mı kaçmak için?\"")
input("\n \"Bilmiyorum. Ben de yeni kendime geldim.\"")
input("\n Biraz etrafa bakındıktan sonra bir havalandırma borusu görüyorsun.")
input("\n	\"Çok iyi gördün knk. İnş sığabiliriz oraya. Biraz dar gibi.\"")
input("\n Ancak 1 kişi geçebilir gibi gözüküyor. Diğeri odada kalmalı ki nöbetçi falan gelirse oyalasın ve diğerinin de orada olduğunu düşünsün.")
input("\n Düşündüğünden daha bir basit şekilde, havalandırma kapağı hemen çıkıyor. Kapağı çıkarırken çivisi eline geliyor. Çiviyi cebine attın.")
input("\n Şimdi sıra gidecek olan kişiyi seçmeye gelmişti.")
gidecek_kişi = int(input("\n***Kim gitmeli?\n(1-Sen, 2-Emir)\n: "))

if gidecek_kişi == 1:
	input("\n \"Ben buradan geçeceğim ve yol varsa kapıyı da açarım. Birisi gelip kapının penceresinden bakarsa, şuradaki yığacağın şu kıyafetleri benmişim gibi uyandırmaya çalış. İnş işe yarar da o yığını ben sanar.\"")
	input("\n	\"Tamam knk çıkar montunu.\"")
	input("\n Montunu çıkardıktan sonra yavaşça havalandırma borusuna giriyorsun. HL3\'ü belki burada sen yapacaksın, sadece levyen eksik.")
	input("\n------------Bölümün sonu-----------")
elif gidecek_kişi == 2:
	input("\n Nöbetçiler gelir de Emir numara yapamaz diye korkuyorsun.")
	input("\n \"Knk sen buradan geçebilir misin?\"")
	input("\n	\"Eee yani geçerim. Biraz küçük ama kayar geçerim diye düşünüyorum.\"")
	input("\n \"Güzel. Yalnız montunu rica edeceğim.\"")
	input("\n	\"Neden?\"")
	input("\n \"Nöbetçi gelirse oluşturacağım yığına ekleyeceğim, inş sen sanar yığını. Bu çiviyi de al, belki işine yarar.\"")
	input("\n \"Ok knk al montu.\"")
	input("\n	Montunu sana verdikten sonra, sessizce havalandırma borusuna giriyor.")
	input("\n------------Bölümün sonu-----------")
